version: "3.3"

services:
    app:
        container_name: testing
        build:
            context: .
            # dockerfile: ${FILE}
        volumes:
            - .:/usr/src/api-testing
            - /usr/src/api-testing/node_modules
        network_mode: "host"


        # "test:ci": "npm run lint && FILE=Dockerfile.Prod docker-compose up --build",